baseURL = 'https://rasmusnuko.github.io'
languageCode = 'en-us'
theme = "hugo-coder"
enableEmoji = true
favicon_32 = "/images/favicon-32x32.png"
favicon_16 = "/images/favicon-16x16.png"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

publishDir = "docs"

# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5

# About
[params]
  author = "Rasmus Nuko"
  title = 'Rasmus Nuko'
  description = "Rasmus Nuko's personal website"
  keywords = "blog,developer,personal"
  info = ["Backend", "Music", "DSP"]
  avatarURL = "/images/me.jpg"
  dateFormat = "January 2, 2006"
  since = 2022

# Socials
[[params.social]]
  name = "Github"
  icon = "fa fa-2x fa-github"
  weight = 1
  url = "https://github.com/rasmusnuko/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-2x fa-linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/nuko/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
